project:
  type: website

website:
  title: "Dash"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_1.qmd
        text: 'Example #1'
      - href: example_2.qmd
        text: 'Example #2'

format:
  html:
    theme: journal
    css: styles.css
    toc: false

editor: visual

